chrome.runtime.onInstalled.addListener(() => {
  // TODO: Download data from Airtable
  // TODO: If website is Google Search...
  // TODO: If website is Google Maps...
  // TODO: If website is Facebook...
  // TODO: If website is Twitter...
  // TODO: If website is LinkedIn...
  // TODO: If website is YouTube...
  // TODO: Else if website matches URL
});
